### PR TITLE
addPercent and subtractPercent now calculates float percentage numbers

### PR DESCRIPTION
**Pull request by alcidesbsilvaneto**
I'm not an expert with Javascript but did my best. 
Just a small change to make addPercent and subtractPercent work with decimal values when using $.

### CODE REVIEW

**Comment by ericelliott** [comment]
Please add a unit test which confirms that the fix worked.

**Comment by alcidesbsilvaneto** [comment]
Just added the test you asked. Do I have to do anything else? I'm just learning about all that git/github mechanics. I just made another commit on the float-percentage-support branch, is that ok?

**Comment by ericelliott** [comment]
These tests (and more decimal percentage tests) pass without your proposed code change. Can you provide an example test that would fail without your code change?

**Comment by ericelliott** [comment]
Closing as invalid. Please reopen if you can come up with a test case that fails.

**Pull request closed without merging**
